# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: carboleda
# "service" is the name of this project. This will also be added to your AWS resource names.
service: aws-serverless-fullstack-app
useDotenv: true

stages:
  default:
    params:
      transactionsTableName: "transactions-table"

custom:
  # "dynamodb" is used by the serverless-dynamodb-local plugin to configure DynamoDB Local.
  dynamodb: ${file(./iac/custom/dynamodb.yml)}

provider:
  name: aws
  runtime: nodejs24.x
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com
  iam: ${file(./iac/permissions/iam.yml)}
  environment:
    TRANSACTIONS_TABLE: ${param:transactionsTableName}
    IS_OFFLINE: ${env:IS_OFFLINE, "false"}
    DYNAMODB_LOCAL_REGION: ${env:DYNAMODB_LOCAL_REGION, ""}
    DYNAMODB_LOCAL_ENDPOINT: ${env:DYNAMODB_LOCAL_ENDPOINT, ""}

functions: ${file(./iac/functions.yml)}

resources:
  - ${file(./iac/resources/dynamodb.yml)}
  # - ${file(./iac/resources/cognito.yml)}

plugins:
  - serverless-dynamodb-local
  - serverless-offline
