export const get = async (event: any) => {
  return {
    statusCode: 200,
    body: JSON.stringify({
      id: 1,
      amount: 100,
      description: "Grocery shopping",
      date: "2024-06-01",
    }),
  };
};

export const getAll = async (event: any) => {
  const userId =
    event.requestContext?.authorizer?.claims?.sub ||
    event.headers?.["x-user-id"] || // FIXME: This is a temporary workaround for local testing. In production, we should rely on the authorizer claims.
    event.pathParameters?.userId;

  if (!userId) {
    return {
      statusCode: 400,
      body: JSON.stringify({ error: "userId is required" }),
    };
  }

  return {
    statusCode: 200,
    body: JSON.stringify([
      {
        id: 1,
        amount: 100,
        description: "Grocery shopping",
        date: "2024-06-01",
      },
      {
        id: 2,
        amount: 50,
        description: "Dinner",
        date: "2024-06-02",
      },
    ]),
  };
};

export const create = async (event: any) => {
  const body = JSON.parse(event.body);
  console.log("Received transaction data:", body);

  const id = "abcd-1234-efgh-5678"; // In a real implementation, this would be generated by the database

  return {
    statusCode: 201,
    body: JSON.stringify({ message: "Transaction created successfully", id }),
  };
};
